(define (a b  c)
	(if (> b c) 
		(display b) 
		(display c))) 

	(a 3 ( + 8 8 ))
	(a 30 ( + 8 8 ))

(define (tail_call depth)
(let (( log (getElementById "log") )) 
	(setInnerHTML log (+ (getInnerHTML log) (string depth)))
	(if (> depth 0)
		(tail_call (- depth 1))
	)
	)
)
(tail_call  1000)
